=== StillKeepTry/XMLHomework/DTD/census1.dtd
<?xml version="1.0" ?>
<!ELEMENT census-record (data, address, person+)>
<!ATTLIST census-record taker CDATA>
	<!ELEMENT date (year, month, day)>
		<!ELEMENT year (#PCDATA)>
		<!ELEMENT month (#PCDATA)>
		<!ELEMENT day (#PCDATA)>
	<!ELEMENT address (street, city, county, country, postalcode)>
		<!ELEMENT street (#PCDATA, unit)>
			<!ELEMENT unit (#PCDATA)>
		<!ELEMENT city (#PCDATA)>
		<!ELEMENT county (#PCDATA)>
		<!ELEMENT country (#PCDATA)>
		<!ELEMENT postalcode (#PCDATA)>
	<!ELEMENT person (name, age, gender)>
	<!ATTLIST person employed kind(fulltime | parttime) #IMPLIED>
	<!ATTLIST person pid ID #REQUIRED>
		<!ELEMENT name (first, last, junior?)>
			<!ELEMENT first (#PCDATA)>
			<!ELEMENT last (#PCDATA)>
			<!ELEMENT junior (#PCDATA)>
		<!ELEMENT age (#PCDATA)>
		<!ELEMENT gender (#PCDATA)>

=== StillKeepTry/XMLHomework/DTD/census1.xml
<?xml version="1.0" ?>
<!DOCTYPE census-record SYSTEM "census1.dtd">
<census-record taker="3163">
  <date><year>2003</year><month>10</month><day>11</day></date>
  <address>
    <street>471 Skipstone Lane <unit>4-A</unit></street>
    <city>Emerald City</city>
    <county>Greenhill</county>
    <country>Oz</country>
    <postalcode>885JKL</postalcode>
  </address>
  <person employed="fulltime" pid="P270405">
    <name>
      <first>Meeble</first>
      <last>Bigbug</last>
      <junior/>
    </name>
    <age>39</age>
    <gender>male</gender>
  </person>
  <person employed="parttime" pid="P273882">
    <name>
      <first>Mable</first>
      <last>Bigbug</last>
    </name>
    <age>36</age>
    <gender>female</gender>
  </person>
  <person pid="P472891">
    <name>
      <first>Marble</first>
      <last>Bigbug</last>
    </name>
    <age>11</age>
    <gender>male</gender>
  </person>
</census-record>
